Repository Alfresco/alfresco-js-api, pull requests merged in 2019-11, with the labels that each got.

#474 Add bpmn test
  .travis.yml
  package-lock.json
  package.json
  scripts/build.sh
  scripts/publish.sh
  scripts/test-integration.sh
  test/integration/test-node/login-bpmn.ts
  test/process-services/taskFormApi.spec.ts
Labels: PR: unreviewed, do not merge

#479 Remove discovery phase
  package-lock.json
  src/authentication/oauth2Auth.ts
  test/mockObjects/oauth2/authResponseMock.js
  test/oauth2Auth.spec.ts
  test/oauth2AuthImplicitFlow.spec.ts
Labels: PR: unreviewed

#480 Promote use await async
  src/alfrescoApi.ts
  src/authentication/oauth2Auth.ts
Labels: PR: unreviewed

#487 Fixing exchange ticket based on provider
  src/authentication/oauth2Auth.ts
  test/oauth2Auth.spec.ts
Labels: PR: reviewed-approved

#489 cleanup package before publishing
  .make-packages.js
  README.md
  package.json
  scripts/build.sh
  scripts/test-build.sh
Labels: PR: reviewed-approved

#483 new integration test for SSO
  scripts/test-integration.sh
  test/integration/test-node/login-ecm.ts
  test/integration/test-node/login-sso.ts
Labels: PR: unreviewed

#490 Add Old link documentation AP1
  README.md
Labels: PR: reviewed-approved

#500 [ADF-4993] User can stay logged in by continuously refreshing the page.
  src/authentication/oauth2Auth.ts
Labels: PR: reviewed-approved

#497 multiinstance test oauth test
  src/authentication/oauth2Auth.ts
  test/mockObjects/oauth2/authResponseMock.js
  test/oauth2Auth.spec.ts
Labels: PR: reviewed-approved

#507 fix minor vulnerability JS-API
  package-lock.json
Labels: PR: reviewed-approved

#510 [ADF-5027] Fix rendition APS 1.X
  src/api/activiti-rest-api/api/content.api.ts
Labels: PR: reviewed-approved
