Repository Alfresco/alfresco-js-api, pull requests merged in 2023-04, with the labels that each got.

#1565 [AAE-13-775] use the gh strategy
  .github/workflows/js-api-build.yml
  .github/workflows/trigger-upstream.yml
  scripts/update-project.sh
Labels: do not merge, PR: unreviewed, PR: partially-approved

#1563 Release of 5.5.0
  docs/audit/audit-info-5.5.0.md
  docs/changelog/changelog-5.5.0.md
  docs/licences/license-info-5.5.0.md
  package-lock.json
  package.json
Labels: PR: partially-approved

#1562 [ACS-4966] Add path to category model
  src/api/content-rest-api/api/categories.api.ts
  src/api/content-rest-api/docs/Category.md
  src/api/content-rest-api/model/category.ts
  test/content-services/categoriesApi.spec.ts
  test/mockObjects/content-services/categories.mock.ts
Labels: PR: unreviewed

#1567 split testing jobs and add error reporting
  .github/workflows/js-api-build.yml
  .gitignore
  test/integration/test-node/login-ecm.ts
  test/integration/test-node/node-content.ts
Labels: PR: partially-approved

#1568 [AAE-13902] - Create the tag using actions
  .github/workflows/js-api-build.yml
  scripts/create-tag.js
Labels: PR: unreviewed, PR: partially-approved

#1572 [AAE-13902] - Create the release tag using the github API
  .github/workflows/js-api-build.yml
  scripts/create-tag.js
  scripts/git-tag.sh
Labels: PR: partially-approved

#1573 [ACS-5040] Renamed one left reference to Alfresco
  definitions/activiti-api.json
Labels: PR: partially-approved

#1574 [ACS-5126] Release 6.0.0
  docs/audit/audit-info-6.0.0.md
  docs/changelog/changelog-6.0.0.md
  docs/licences/license-info-6.0.0.md
  package-lock.json
  package.json
Labels: PR: reviewed-approved
