Repository Alfresco/alfresco-js-api, pull requests merged in 2023-03, with the labels that each got.

#1535 [ACS-4723] Remove fs-extra dependency
  .make-packages.js
  package-lock.json
  package.json
Labels: PR: partially-approved

#1536 [ACS-4724] remove minimatch dependency
  README.md
  docs/licences/license-info-5.1.0.md
  package-lock.json
  package.json
  src/authentication/oauth2Auth.ts
  src/utils/path-matcher.ts
  test/oauth2Auth.spec.ts
  test/path-matcher.spec.ts
Labels: PR: partially-approved

#1538 Publish js pkg on gh pkg registry [Do Not merge]
  .github/workflows/js-api-build.yml
  scripts/publish.sh
Labels: PR: unreviewed

#1542 Rely on action to create npmrc
  .github/workflows/js-api-build.yml
  scripts/publish.sh
Labels: PR: partially-approved

#1543 Inverte release order
  .github/workflows/js-api-build.yml
Labels: PR: unreviewed

#1544 Npm publish: Use token as part of workflow
  .github/workflows/js-api-build.yml
  scripts/publish.sh
Labels: PR: unreviewed

#1534 [ADF-5515] Integration test for js api working
  .github/workflows/js-api-build.yml
  test/integration/test-node/login-ecm.ts
  test/integration/test-node/login-sso.ts
  test/integration/test-node/node-content.ts
  test/integration/test-node/upload-file.ts
Labels: PR: unreviewed

#1545 [AAE-12501] Align JS API
  README.md
  src/alfrescoApi.ts
  src/alfrescoApiConfig.ts
Labels: PR: unreviewed

#1546 [ACS-4753] list of tags is not rendered because of missing count field in backend response
  src/api/content-rest-api/api/tags.api.ts
  test/content-services/tagApi.spec.ts
  test/mockObjects/content-services/tag.mock.ts
Labels: PR: unreviewed, PR: partially-approved

#1549 [ACS-4117] Creating multiple subcategories
  src/api/content-rest-api/api/categories.api.ts
  src/api/content-rest-api/docs/CategoriesApi.md
  test/content-services/categoriesApi.spec.ts
Labels: PR: partially-approved
